tmobile/t-vault

tvaultui/src/app/Common/Directives/Resize/Resize.directive.js
tvaultui/src/app/Common/Directives/dateTimeFilter/dateTimeFilter.directive.js
tvaultui/src/app/Common/Directives/listTable/listTable.directive.js
tvaultui/src/app/Common/Directives/loadingState/loadingState.directive.js
tvaultui/src/app/Common/Directives/navBar/navBar.directive.js
tvaultui/src/app/Common/Directives/radioButtons/radioButtons.directive.js
tvaultui/src/app/Common/Directives/restrictSpecialChar/restrictSpecialChar.js
tvaultui/src/app/Common/Directives/sidebar/sidebar.directive.js

Added semicolons at the end of the modules declarations to avoid issue while minifying the js files.

Added semicolons at the end of the modules declarations

---

tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/safes/safes.data.js
tvaultui/src/app/Features/safes/safes.service.js

1. changed key name to 'apps' from 'app'
2. admin documentation link redirected to swagger

Staging - bugfixes

---

build_tvault.sh

Fixed a copy/paste error - check is for node but message said java.

Fixed confusing error message

---

tvaultui/src/apiUrls.json
tvaultui/src/app/Common/Constants/RestEndpoints/RestEndpoints.constant.js
tvaultui/src/app/Common/Directives/tiles/tiles.directive.js
tvaultui/src/app/Common/Directives/tiles/tiles.jade
tvaultui/src/app/Common/Directives/tiles/tiles.scss
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/admin/admin.jade
tvaultui/src/app/Features/admin/admin.scss
tvaultui/src/assets/Icons/front-arrow.svg

- Admin - Dropdown to select user safe, application safe and shared safe to be removed
- To add tabs for navigating between User safe, Shared Safe and Application Safe.
- To hide the option for user to shift between tabular view and tile view. By default only tile view will be visible.
- To display Show more options below which will be absolutely positioned:

Admin - pagination changes

---

tvaultapi/pom.xml
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/AccessController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/AppRoleController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/LDAPAuthController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SDBController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SecretController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SysController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/UserPassController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/VaultAuthController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/exception/LogMessage.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/process/RequestProcessor.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/process/RestProcessor.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AccessService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AppRoleService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/LDAPAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SecretService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SysService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/UserPassService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/LogMessageUpdater.java
tvaultapi/src/main/resources/log4j2-spring.xml

Code is updated to remove sensitive logs and also Logger is updated to support proper json format

Changes to remove logging of possible sensitive info 

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SecretService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SecretControllerV2.java

updated V2 endpoints for secrets

---

tvaultui/src/app/Common/Constants/RestEndpoints/RestEndpoints.constant.js
tvaultui/src/app/Common/Directives/footer/footer.directive.js
tvaultui/src/app/Common/Directives/tiles/tiles.directive.js
tvaultui/src/app/Common/Services/ServiceEndpoints/ServiceEndpoints.service.js
tvaultui/src/app/Common/Services/SessionStore/SessionStore.service.js
tvaultui/src/app/Common/Services/VaultServices/VaultUtility/VaultUtility.service.js

Made few changes which would work normally but fails while minifying.

Javascript minification was failing.

---

dist/src/main/components/hcorp/bin/tvault
dist/src/main/docker/vault.sh
tvaultapi/pom.xml
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ResponseExceptionHandler.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SDBController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/exception/TVaultValidationException.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSAuthLogin.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSAuthType.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSClientConfiguration.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSIAMLogin.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSIAMRole.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSStsRole.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AWSTempCredential.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSIAMAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/AWSAuthControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/AWSIAMAuthControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/DirectoryServiceControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SDBControllerV2.java
tvaultapi/src/main/resources/application.properties
tvaultapi/src/main/resources/com/tmobile/cso/vault/api/config/api_config.json
tvaultui/src/app/Features/change-safe/change-safe.controller.js
tvaultui/src/app/Features/change-safe/change-safe.jade

Changes:
1. IAM Authentication
2. Upgraded vault
3. Code refactoring

IAM Authentication

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SDBController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java

1. Safe creation problem
2. User association problem

Defect fixes

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/LDAPAuthController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/SDBController.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/LDAPAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java

This is the continuation of PR #56 (Applied to other places)

Fix for issues with Safe creation, edit, delete

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AppRole.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/validator/TokenValidator.java
tvaultapi/src/main/resources/application.properties

Fix to allow - in safe names, typo error

---

tvaultapi/pom.xml
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AWSAuthServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AWSIAMAuthServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AccessServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/DirectoryServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/LDAPAuthServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SafesServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SecretServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SysServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/UserPassServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/VaultAuthServiceTest.java

Unit test cases for Tvault API and added jacoco plugin to tvaultapi pom

Unit test cases for Tvault API

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/filter/TokenValidationFilter.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SelfSupportService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/VaultAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/AuthorizationUtils.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/PolicyUtils.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/SafeUtils.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/TokenUtils.java

Fixed: 1. When a safe is created, it was not appearing in UI, 2. isAuthorized() not handling safe-creation owners

Safes Listing issue

---

dist/src/main/components/hcorp/conf/approle_normal_user.json
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/AuthorizationUtils.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/TokenUtils.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/utils/AuthorizationUtilsTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/utils/TokenUtilsTest.java

More Unit test cases

---

dist/src/main/components/hcorp/conf/selfservicesupport_policy.json
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SelfSupportService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v3/controller/SelfSupportController.java

1. End point to get all the safes
2. AppRole policy

More Self-support changes

---

tvaultapi/src/test/java/com/tmobile/cso/vault/api/controller/ControllerUtilTest.java

Corrected failed test cases (failing due to stale value set)

Code refactoring to address vulnerabilities

---

tvaultui/src/app/Features/change-safe/change-safe.jade
tvaultui/src/app/Features/change-safe/change-safe.scss
tvaultui/src/app/Features/safes/safes-folders/safes-folders.controller.js
tvaultui/src/app/Features/safes/safes.scss
tvaultui/src/app/Layout/base/base.jade
tvaultui/src/app/sass/common.scss

Mandatory icons are marked and safe edit name min length validation removed.
In Admin, safes are displayed as 5 on each row.

Mandatory icons are marked and safe edit name min length validation removed.

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/TVaultConstants.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AppRoleAccessorId.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AppRoleAccessorIdSecretId.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AppRoleAccessorIds.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AppRoleDetails.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/process/RequestProcessor.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AppRoleService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SelfSupportService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/AuthorizationUtils.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/AppRoleControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportController.java
tvaultapi/src/main/resources/application.properties
tvaultapi/src/main/resources/com/tmobile/cso/vault/api/config/api_config.json
tvaultapi/src/test/java/com/tmobile/cso/vault/api/controller/ControllerUtilTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AppRoleServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SelfSupportServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/AppRoleControllerV2Test.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportControllerTest.java

Added the end points for readRoleId, readSecretId, readAppRoleDetails, readAppRoleMetada, readAccessorIds, deleteAccessorIds,

ApplRole code refactoring

---

dist/src/main/components/hcorp/conf/server_consul.hcl

Flag added to disabled vault registration with Consul

flag added to disable registration

---

build_tvault.sh

Hashicorp vault 1.2 upgrade issues

---

dist/src/main/components/hcorp/bin/tvault

Reverted changes done for 1.2 upgrade

Removed unzip code block

---

tvaultui/src/app/Features/change-service-account/change-service-account.controller.js

Removed hard coded service account name

Corrected hard coded account name to be searched

---

tvaultui/src/app/Features/admin/admin.jade
tvaultui/src/app/Features/change-service-account/change-service-account.controller.js
tvaultui/src/app/Features/change-service-account/change-service-account.jade

Improved UI messages for Service Account Password Rotation

Updated the messages

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/main/WebConfig.java

Added bean definition for JavaMailSender

Added bean definition for JavaMailSender

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/ServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/EmailUtils.java
tvaultapi/src/main/resources/application.properties

Enhanced Email Message

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/EmailUtils.java

Fix for images not shown in email message

Fix for images not shown in email message

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/WorkloadAppDetails.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/WorkloadDetailsService.java
tvaultui/src/app/Features/admin/admin.jade
tvaultui/src/app/Features/admin/manage.jade
tvaultui/src/app/Features/change-service-account/change-service-account.jade

Corrected messages and added default appname called "other"

Corrected messages and added default appname

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/WorkloadDetailsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/WorkloadDetailsController.java
tvaultapi/src/main/resources/application.properties

Workload details changed to use latest API

Workload details changed

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/ServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/EmailUtils.java
tvaultui/src/app/Features/change-safe/change-safe.jade
tvaultui/src/app/Features/change-service-account/change-service-account.jade

Fix for hiding sudo permission in user permission
Removed userId creation from email in service account
Removed pink-text from aws & approle name in permission list

Added exception handling for service account mail sender, fix for sudo permission, service account user id

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/CertificateData.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/SSLCertMetadata.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/SSLCertificateMetadataDetails.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/SSLCertificateRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/TargetSystem.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SSLCertificateServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SSLCertificateControllerTest.java
tvaultui/src/app/Features/admin/admin.controller.js

Provided fix for defects COCICCS-2273,COCICCS-2274

COCICCS-2273,COCICCS-2274 provided fix

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/SSLCertificateConstants.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/process/RequestProcessor.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/admin/manage.jade

COCICCS-2323 : Enable Certificate Creation option for normal users

COCICCS-2323 : Enable Certificate Creation option for normal users

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java

Certificate Creation : policy creation token issue for normal user : fixed

Certificate Creation : policy creation token issue for normal user : fixed

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/WorkloadDetailsService.java
tvaultapi/src/main/resources/application.properties
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/admin/admin.jade
tvaultui/src/app/Features/admin/admin.scss
tvaultui/src/app/Features/admin/manage.jade

Only for review. Will be rebased with the existing PR once that is merged.

Updated bug fixes for target system menu

---

tvaultui/src/app/Features/admin/admin.controller.js

Revert "Fix to Enable/Disable monitoring flags"

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultui/src/app/Features/admin/admin.controller.js

Revert "Bug Fixes:Create Certificate Issues"

---

dist/src/main/components/hcorp/conf/selfservicesupport_policy.json
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/GroupAliasRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/OIDCEntityRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/OIDCIdentityGroupRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/OIDCLookupEntityRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/OIDCAuthService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/OIDCAuthController.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/OIDCAuthServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/OIDCAuthControllerTest.java

Wrapper Api's for oidc authentication

Oidc authentication

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultapi/src/main/resources/templates/TransferTemplate.html
tvaultapi/src/test/java/com/tmobile/cso/vault/api/controller/OIDCUtilTest.java
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/admin/admin.jade
tvaultui/src/app/Features/admin/admin.scss
tvaultui/src/app/Features/admin/manage.jade

Revert "Defect fixes for create certificate"

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/CertificateUpdateRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SSLCertificateController.java
tvaultapi/src/main/resources/application.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SSLCertificateServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SSLCertificateControllerTest.java
tvaultui/src/app/Common/Constants/RestEndpoints/RestEndpoints.constant.js
tvaultui/src/app/Common/Services/VaultServices/Admin/AdminSafesManagement.service.js
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/change-certificate/change-certificate.controller.js
tvaultui/src/app/Features/change-certificate/change-certificate.jade
tvaultui/src/app/Features/change-certificate/change-certificate.scss

view/edit page ui and api changes and certificate load issue fix

COCICCS-4488,COCICCS-4679

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/AzureServiceAccountConstants.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/AzureServiceAccountOffboardRequest.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AzureServicePrinicipalAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/AzureServicePrinicipalAccountsController.java
tvaultapi/src/main/resources/application.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AzureServicePrinicipalAccountsServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/AzureServicePrinicipalAccountsControllerTest.java

Offboard AAD Service Principal with test cases

COCICCS-4453 : Offboard AAD Service Principal

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
tvaultui/src/app/Features/admin/admin.controller.js
tvaultui/src/app/Features/change-certificate/change-certificate.controller.js
tvaultui/src/app/Features/change-certificate/change-certificate.jade

Revert "view/edit updates"

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SelfSupportService.java
tvaultapi/src/main/resources/swaggernotes.properties

Swagger note and invalid owner email changes

COCICCS - 6307 Defect fix for the API Update issues 

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/model/IAMServiceAccount.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsControllerTest.java

Additional characters +=,.@ allowed for IAMServiceAccount username

Additional characters +=,.@ allowed for IAMServiceAccount username

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/OIDCUtil.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/IAMServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsController.java
tvaultapi/src/main/resources/swaggernotes.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/IAMServiceAccountServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsControllerTest.java

To get list of IAM Service accounts onboarded into T-Vault

Added new listing API for getting list of IAM Service accounts

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/IAMServiceAccountConstants.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/IAMServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsController.java
tvaultapi/src/main/resources/swaggernotes.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/IAMServiceAccountServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsControllerTest.java

API support added to write/add AccessKey to IAM Service Account

Added API to add AccessKey to IAM Service Account

---

tvaultuiv2/src/views/private/safe/components/Tabs/index.js

…e is not in the first 20 safes

Fix for permission tab disappearing for admin users when the safe name is not in the first 20 safe list

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AppRoleService.java
tvaultapi/src/main/resources/swaggernotes.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AppRoleServiceTest.java

Changes to improve code coverage and remove "code smells" that were determined by SonarQube. There are more PRs to follow with additional test classes.
Also adding bug fixes for AppRole changes.

Code coverage improvements - AppRoleService

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/IAMServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/IAMServiceAccountUtils.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/IAMServiceAccountServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/utils/IAMServiceAccountUtilsTest.java

Improving code coverage in two large files to help get our coverage to > 80% as measured by SonarQube

Further code coverage improvements

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/IAMServiceAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsController.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/IAMServiceAccountServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/IAMServiceAccountsControllerTest.java

IAM : GetAccessKeys API - When given read access to the user, it is throwing error as No Iam Service Account with svc_iam_tvaulttestuser1.

Fixing COCICCS-9690 issue 1 - GetAccessKeys API

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SSLCertificateController.java
tvaultapi/src/main/resources/swaggernotes.properties
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SSLCertificateControllerTest.java
tvaultuiv2/src/views/private/azureprincipal/component/AzureSelectionTabs/index.js
tvaultuiv2/src/views/private/certificates/components/CertificatesDashboard/index.js

Removing unneeded API endpoints, removing "Onboard" certs page, fixing ASP permissions tab issue for COCICCS-10224.

Removing unneeded API endpoints, fixing ASP permissions tab issue

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SecretService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SelfSupportService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SDBControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SecretControllerV2.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportController.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SafesServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SecretServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/SelfSupportServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SDBControllerV2Test.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SecretControllerV2Test.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportControllerTest.java
tvaultuiv2/src/resources/index.js
tvaultuiv2/src/views/private/safe/CreateSafe/index.js
tvaultuiv2/src/views/private/safe/components/SafeDashboard/index.js
tvaultuiv2/src/views/private/safe/components/SafeDetails/index.js
tvaultuiv2/src/views/private/safe/components/Secrets/index.js
tvaultuiv2/src/views/private/safe/components/Tabs/index.js
tvaultuiv2/src/views/private/safe/components/Tree/components/file.jsx
tvaultuiv2/src/views/private/safe/components/Tree/components/folder.jsx
tvaultuiv2/src/views/public/HomePage/index.js

Reverting safe decommission changes in dev, because these changes will not go into production until after our ASP release.

Reverting safe decommission changes for Dev

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AzureServicePrincipalAccountsService.java
tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/AzureServicePrincipalAccountsController.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/service/AzureServicePrincipalAccountsServiceTest.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/AzureServicePrincipalAccountsControllerTest.java

Fix for "Perf: ASP: When given deny permissions via user/group deny then admin is getting denied" : https://jirasw.t-mobile.com/browse/COCICCS-10609

Fix for ASP Admin Deny Permission Bug

---

tvaultuiv2/src/views/private/azureprincipal/component/AzureSelectionTabs/index.js

Fixing ASP Onboard Issue

---

tvaultuiv2/src/views/private/azureprincipal/component/AzureSelectionTabs/index.js

Fixed small condition for ASP

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AzureServicePrincipalAccountsService.java

Adding logging for ASP service to help diagnose an issue that seems to be environment-specific.

Adding Logging for ASP Service

---

tvaultuiv2/src/views/private/azureprincipal/component/AzureSelectionTabs/index.js

Fix for ASP Refresh Issue

---

tvaultuiv2/src/views/private/azureprincipal/component/AzureSelectionTabs/index.js

Fix for ASP Refresh Issue in Release Branch

Fix for ASP Refresh Issue in Release Branch

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportController.java
tvaultapi/src/test/java/com/tmobile/cso/vault/api/v2/controller/SelfSupportControllerTest.java
tvaultuiv2/src/views/private/safe/components/SafeDashboard/index.js
tvaultuiv2/src/views/public/HomePage/index.js

Cso release 1.4.21

---

tvaultuiv2/src/views/private/safe/components/SafeDashboard/index.js

safe decommision bug fix

---

tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/IAMServiceAccountsService.java

iam secret expiry bug fix
